### ISSUE TITLE
Encode/Decode byte[]

### ISSUE THREAD

**Issue by iamadamreed** [Krusen/BencodeNET#11]
By only allowing the library to decode a stream or a string, it is very limited. I have a nice `MessageRecieved` method that provides a `byte[] message, IPEndPoint source` and I am unable to make use of the library as I provide the raw message from the `UdpClient`. It would be nice to see an additional overload that can Decode the provided message.

The same goes for the following code: 

```
       public void FindNode(IPEndPoint endPoint)
        {
            var data = new BDictionary()
            {
                {"t", "aa"},
                {"y", "q"},
                {"q", "find_node"},
                {
                    "a",
                    new BList()
                    {
                        new BString(NodeId)
                    }
                }

            };

            using (MemoryStream ms = new MemoryStream())
            {
                data.EncodeToStream(ms);
                _udp.SendAsync(ms.ToArray(), endPoint);
                Console.WriteLine($"[FindNode] Sending to {endPoint.Address}");
            }
        }
```

It would be nice to have a function such as `data.GetBytes()`;

**Comment by iamadamreed** [comment]
You might want to add the example usage of this to the Documentation front page =D

**Comment by Krusen** [comment]
@adamreed90 Yes, I still need to update the readme/documentation for 2.0, but I'm waiting until it's all done - I still need to finish a few minor things and I also have an upcoming vacation, so it will be a few weeks still.

**Comment by iamadamreed** [comment]
Thanks @Krusen
