### ISSUE TITLE
Package BencodeNET 1.3.1 is not compatible with netcoreapp1.0

### ISSUE THREAD

**Issue by vy0b0x** [Krusen/BencodeNET#13]
Hello, I installed BencodeNET 1.3.1 via nuget on .net core, and I got an error about compatible.
C:\Program Files\dotnet\dotnet.exe restore "F:\c#\asdf.vs\restore.dg"
log  : Restoring packages for F:\c#\asdf\src\asdf\project.json...
error: Package BencodeNET 1.3.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package BencodeNET 1.3.1 supports:
error:   - net35 (.NETFramework,Version=v3.5)
error:   - net40 (.NETFramework,Version=v4.0)
error:   - net45 (.NETFramework,Version=v4.5)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
log  : Writing lock file to disk. Path: F:\c#\asdf\src\asdf\project.lock.json
log  : F:\c#\asdf\src\asdf\asdf.xproj
log  : Restore failed in 553ms.
Errors in F:\c#\asdf\src\asdf\asdf.xproj
    Package BencodeNET 1.3.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package BencodeNET 1.3.1 supports:
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Anything can fix that?
Thanks.

**Comment by Krusen** [comment]
.NET Core support has been added in the upcoming v2.0. You can install the pre-release version 2.0.1-beta from NuGet if you enable pre-release versions.

Please note that the API has changed and the current README is not up to date. Version 2.0 will be released soon with an updated README with correct examples.

Here are a few examples for how to use v2.0.

---

Working with torrents.

``` C#
// Parse torrent by specifying the file path
var parser = new BencodeParser(); // Default encoding is Encoding.UT8F, but you can specify another if you need to
var torrent = parse.Parse<Torrent>("C:\ubuntu.torrent");

// Calculate the info hash
string infoHash = torrent.CalculateInfoHash();
// "B415C913643E5FF49FE37D304BBB5E6E11AD5101"
```

Simple parsing of a bencoded string:

``` C#
var parser = new BencodeParser();
BString bstring = parser.ParseString("12:Hellow World!");
// "Hello World!" (BString)

// If you know the type of the bencode you are parsing, you can use the generic version of `ParseString()` instead.
var bstring2 = parser.ParseString<BString>("12:Hello World!");
// "Hello World!" (BString)

var bnumber = parser.ParseString<BNumber>("i42e");
// 42 (BNumber)

var blist = parser.ParseString<BList>("l3:foo3:bari42ee");
// { "foo", "bar", 42 } (BList)

var bdictionary = parser.ParseString<BDictionary>("d3:fooi42e5:Hello6:World!e");
// { { "foo", 42 }, { "Hello", "World" } } (BDictionary)
```

If you are unsure of the type you can just use the non-generic version:

``` C#
IBObject bobject = parser.ParseString("12:Hello World!");

if (bobject is BString)
{
    // The parsed object is a string
}
```

**Comment by vy0b0x** [comment]
Really help me, thanks for your patience and this project. :)
