### ISSUE TITLE
Torrent pieces property returns wrong value

### ISSUE THREAD

**Issue by cnaos** [Krusen/BencodeNET#18]
I'm using v2.1.0.

```
var parser = new BencodeParser();
var torrent = parser.Parse<Torrent>("Files\\ubuntu-14.10-desktop-amd64.iso.torrent");
string pieces = torrent.Pieces;
int piecesLength = pieces.Length;
System.Diagnostics.Debug.WriteLine($"piecesLength = {piecesLength}");
```

torrent.Pieces.length must be 44380, but returns 42014.

ubuntu-14.10-desktop-amd64.iso.torrent
is same as those in the BencodeNET.Tests.

**Comment by Krusen** [comment]
I've put out a new release (2.2.0) which fixes this and changes `Torrent.Pieces` to a `byte[]`. I've also added a new property `Torrent.PiecesAsHexString`.
