### ISSUE TITLE
Announce vs AnnounceList

### ISSUE THREAD

**Issue by Thibach** [Krusen/BencodeNET#24]
Hi
Thank for your great job ! Very usefull and well documented
I'm writing a tool able to replace trackers in a list of torrent files. But I've found an issue when there is only one tracker defined. AnnouceList is not set. I understand that could be logical but client torrent (as qbittoorent) don't use Announce but AnnounceList. In this case, no tracker are detected by the torrent client.
I've changed locally with trackerCount > 0) for AnnouceList.
Best regards

Tracker.cs
```
 if (trackerCount > 0)
               torrent[TorrentFields.Announce] = ...
if (trackerCount > 1)
               torrent[TorrentFields.AnnounceList] = ...
```

**Comment by Krusen** [comment]
The `announce` entry is default and should be supported by all clients and always be set. `announce-list` is an optional extension to the official specification to support more than one tracker.
