### ISSUE TITLE
Torrent file 'announce' field is always encoded as list, not as string

### ISSUE THREAD

**Issue by ilyabreev** [Krusen/BencodeNET#30]
If I need to create torrent object:

```
var trackers = new List<IList<string>>()
{
    new List<string>()
    {
        "TRACKER.URL"
    }
};
var torrent = new Torrent()
{
    CreationDate = DateTime.Now,
    IsPrivate = true,
    Trackers = trackers,
    PieceSize = 524288,
    File = new SingleFileInfo
    {
        FileSize = file.Length,
        FileName = file.Name
    }
};
```

and then after calculating hashes write it to a file:
```
torrent.EncodeTo(torrentFile);
```

then 'announce' field of a torrent will be a list and torrent clients won't recognize tracker URL

**Comment by Krusen** [comment]
You are right. I'll try to get this fixed this weekend.

You are also welcome to submit a PR. [This is the line that needs to be changed](https://github.com/Krusen/BencodeNET/blob/master/BencodeNET/Torrents/Torrent.cs#L231).

**Comment by ilyabreev** [comment]
Yeah, found it already. Thinking about good test case.

**Comment by ilyabreev** [comment]
opened #31

**Comment by ilyabreev** [comment]
It would be great if you update the nuget package.

**Comment by Krusen** [comment]
Done.

You can also access each build on my myget feed as well.

- https://www.myget.org/F/krusen/api/v3/index.json
- https://www.myget.org/F/krusen/api/v2
