### ISSUE TITLE
Getting Magnet / Torrent stream url.

### ISSUE THREAD

**Issue by Kajirinn** [Krusen/BencodeNET#36]
Hi there, first of all I'd like to thank you for taking the time to create such an awesome tool. After looking at a few examples I came to the conclusion that I can't really figure it out myself.

I'd like to get the stream url from either a torrent or preferably a magnet link. How would one achieve this?

Thanks in advance,

Kajirinn.

**Comment by Krusen** [comment]
"Streaming" is a client implementation feature - i.e. using the info in a torrent file to connect to peers and download/stream the file(s) of the torrent.

Here's an example client: https://webtorrent.io/

**Comment by Vishvjeet42** [comment]
http://pairing:851679E405A411EEB59834D9BC9117EF455B028D@127.0.0.1:26240/proxy?sid=109f7f04&file=0&token=851679E405A411EEB59834D9BC9117EF455B028D&pairing=851679E405A411EEB59834D9BC9117EF455B028D&service=STREAMING
