### ISSUE TITLE
Creating Torrent?

### ISSUE THREAD

**Issue by WatchSoMuch** [Krusen/BencodeNET#37]
I am using your code but it seems while creating torrent, calculating and adding pieces is not implemented yet? or maybe Im wrong, I had to calculate and add pieces manually, I mean isn't really a method to pass a folder name and it adds files and pieces for you?

**Comment by Krusen** [comment]
This library was never meant to be about torrent files specifically, just the Bencode format. At some point I added in some functionality to make it easier to read/modify torrent files, but the library can't create torrent files for you - at least not for now - you need another library for that.

**Comment by WatchSoMuch** [comment]
Thank you, but you have underestimated your library, I have done it in few hours using your library, was a bit tricky on piece hashes.
Unfortunately because the code I was adding this feature was VB.NET I didn't add it to cour code byt can paste it here not much of a beautiful code, but created few multifile torrents and now the checking is complete everything works fine

    Public Shared Function CreateTorrentFromFolder(title As String,pieceLength as integer, folder As DirectoryInfo, ByRef err As String) As Torrents.Torrent
        Try
            Dim torrent = New Torrents.Torrent()
            torrent.CreationDate = DateTime.Now

            torrent.Files = New MultiFileInfoList(title)

            Dim fnumber As Integer = 0
            Dim previousBuffer() As Byte
            Dim allFiles = folder.GetFiles()
            For Each file As FileInfo In allFiles
                fnumber += 1
                Dim extraFile = New MultiFileInfo()
                extraFile.FullPath = file.FullName
                extraFile.FileSize = file.Length
                extraFile.Path = New List(Of String)
                extraFile.Path.Add(file.Name)

                torrent.Files.Add(extraFile)
                torrent.PieceSize = pieceLength

                Dim length As Integer
                Dim buf As Byte() = New Byte(torrent.PieceSize - 1) {}
                Using sha1 As New SHA1Managed()
                    Using fs As New FileStream(file.FullName, FileMode.Open)
                        If previousBuffer Is Nothing Then
                            length = fs.Read(buf, 0, torrent.PieceSize)
                        Else 'the last buffer from previous file needs to be concatenated to new file
                            Array.Resize(buf, torrent.PieceSize - previousBuffer.Length)
                            length = fs.Read(buf, 0, torrent.PieceSize - previousBuffer.Length)
                            length += previousBuffer.Length
                            buf = previousBuffer.Concat(buf).ToArray()
                            previousBuffer = Nothing
                        End If
                        While length > 0
                            If length < torrent.PieceSize Then 'last buffer for the file
                                If fnumber < allFiles.Length Then 'hash it only if its last file
                                    previousBuffer = New Byte(length - 1) {}
                                    Array.Copy(buf, previousBuffer, length)
                                    Continue For
                                else
                                    Array.Resize(buf, length)
                                End If
                            End If
                            Dim hash As Byte() = sha1.ComputeHash(buf)
                            'may be written better
                            If (torrent.Pieces Is Nothing) Then
                                torrent.Pieces = hash
                            Else
                                torrent.Pieces = torrent.Pieces.Concat(hash).ToArray()
                            End If
                            'buffer was resized on last buffer so we reset the size to piece length
                            ReDim buf(torrent.PieceSize - 1)

                            'in vb we have to write it twice to make the while work
                            length = fs.Read(buf, 0, torrent.PieceSize)
                        End While

                    End Using
                End Using

            Next

            'Add some trackers
            torrent.Trackers.Add(TrackerList)

            Return torrent

        Catch ex As Exception
            err = ex.Message
        End Try
    End Function

**Comment by Krusen** [comment]
Cool. I might add something like that to this library at some point in the future.

**Comment by Wiilf** [comment]
C#. Visual Studio plugin. It's done me wonders many times. This is the output. I'll see what I can make of this on a button event. Awesome library, big thanks!
```
public static Torrent CreateTorrentFromFolder(string title, int pieceLength, DirectoryInfo folder, ref string err)
        {
            try
            {
                var torrent = new Torrent()
                {
                    CreationDate = DateTime.Now,
                    Files = new MultiFileInfoList(title)
                };
                int fnumber = 0;
                var previousBuffer = default(byte[]);
                var allFiles = folder.GetFiles();
                foreach (FileInfo file in allFiles)
                {
                    fnumber += 1;
                    var extraFile = new MultiFileInfo()
                    {
                        FullPath = file.FullName,
                        FileSize = file.Length,
                        Path = new List<string>()
                    };
                    extraFile.Path.Add(file.Name);
                    torrent.Files.Add(extraFile);
                    torrent.PieceSize = pieceLength;
                    int length;
                    var buf = new byte[(int)(torrent.PieceSize - 1L + 1)];
                    using (var sha1 = new SHA1Managed())
                    {
                        using (var fs = new FileStream(file.FullName, FileMode.Open))
                        {
                            if (previousBuffer is null)
                            {
                                length = fs.Read(buf, 0, (int)torrent.PieceSize);
                            }
                            else // the last buffer from previous file needs to be concatenated to new file
                            {
                                Array.Resize(ref buf, (int)(torrent.PieceSize - previousBuffer.Length));
                                length = fs.Read(buf, 0, (int)(torrent.PieceSize - previousBuffer.Length));
                                length += previousBuffer.Length;
                                buf = previousBuffer.Concat(buf).ToArray();
                                previousBuffer = null;
                            }

                            while (length > 0)
                            {
                                if (length < torrent.PieceSize) // last buffer for the file
                                {
                                    if (fnumber < allFiles.Length) // hash it only if its last file
                                    {
                                        previousBuffer = new byte[length];
                                        Array.Copy(buf, previousBuffer, length);
                                        continue;
                                    }
                                    else
                                    {
                                        Array.Resize(ref buf, length);
                                    }
                                }

                                var hash = sha1.ComputeHash(buf);
                                // may be written better
                                if (torrent.Pieces is null)
                                {
                                    torrent.Pieces = hash;
                                }
                                else
                                {
                                    torrent.Pieces = torrent.Pieces.Concat(hash).ToArray();
                                }
                                // buffer was resized on last buffer so we reset the size to piece length
                                buf = new byte[(int)(torrent.PieceSize - 1L + 1)];

                                // in vb we have to write it twice to make the while work
                                length = fs.Read(buf, 0, (int)torrent.PieceSize);
                            }
                        }
                    }
                }

                // Add some trackers
                torrent.Trackers.Add((IList<string>)"http://domain.com/announce");
                return torrent;
            }
            catch (Exception ex)
            {
                err = ex.Message;
            }

            return default;
        }
```
