### ISSUE TITLE
.NET Core memory accelation support

### ISSUE THREAD

**Issue by sgjsakura** [Krusen/BencodeNET#38]
Hi, I'm now working on an implementation for .NET Core Tracker server, and since there's some important performance enhancement in .NET Core 2.2 (or .NET Standard 2.1), is there any plan to support them? 

Some known memory acceleation manner in .NET Core 2.2 includes:
- using System.Span<T> to store and slice bytes and strings.
- Using ArrayPool to re-use array buffers.
- Using PipeReader to read byte sequences from stream pipelines.

 Maybe the parsing system should make some API changes in order to support them.

Best regards,

**Comment by Krusen** [comment]
Hi Sakura

It's something I've been thinking about looking into but never gotten
around to.
I've just started looking at this yesterday after receiving your mail.

If you have any specific API changes in mind regarding this I'd like to
know.

Best regards
Søren Kruse


Den fre. 26. jul. 2019 kl. 10.40 skrev Sakura Iris <notifications@github.com

**Comment by sgjsakura** [comment]
Hi Krusen, actually I'm tried to build a new version of BEncoding (de)serialization library before, however since the BEncoding is not a well-formed encoding system, it's hard to implement the token analyzation. Besides, I'd also like to see the high-level CLR type mapping for BEncoding (e.g. automatically (de)serialize a string property for an object, etc.)

The [`System.Text.Json` library](https://github.com/dotnet/corefx/tree/master/src/System.Text.Json) implemented by the .NET official team should be a good sample using most of memory accelation techinques including `Span<T>`, `ref struct` and `PipeReader`, etc. Maybe it can help, although the code is lack of comments and instructions lol.

Best regards, and I'm also looking forward to collaboration.
Iris Sakura
