### ISSUE TITLE
Prefer "name.utf-8" and "path.utf-8" over their non-"utf-8" counterparts?

### ISSUE THREAD

**Issue by miehler** [Krusen/BencodeNET#47]
I compared BencodeNET with quite some libraries to parse a whole lot of torrents. While mostly Bencode delivers the best results in some cases other libraries worked better when decoding paths and filenames. As it turns out MonoTorrent for example seems to prefer the "name.utf-8" and "path.utf-8" entries (if present!) over their non-"utf-8" counterparts.

Knowing that Bencode primarily wasn't meant as a torrent library: Is there any chance that this behaviour will be implemented in BencodeNET?

**Comment by Krusen** [comment]
I could probably add that.

I'm thinking of just adding a `SingleFileInfo.FileNameUtf8` and `MultiFileInfo.PathUtf8` property (and matching UTF8 properties `FileNameUtf8`, `FullPathUtf8`). Then it's up to you to decided which one to use or have some sort of fallback from one to the other.

Would that work?

**Comment by miehler** [comment]
That's even better! Thanks a lot!

**Comment by miehler** [comment]
Could you maybe add a property `MultiFileInfoList.DirectoryNameUtf8`, too? It's needed to get the proper display name...

    public string DisplayName(Torrent torrent)
    {
        switch (torrent.FileMode)
        {
            case TorrentFileMode.Single:
                return torrent.File.FileNameUtf8;
            case TorrentFileMode.Multi:
                return torrent.Files.DirectoryNameUtf8;
            default:
                throw new InvalidTorrentException("Unknown file mode.");
        }
    }

Thanks a lot!

**Comment by miehler** [comment]
Unfortunately there are two more bugs resulting from the UTF8 change :/

The first one must be fixed to be able to parse torrents that do not contain UTF8 names at all:

`DirectoryNameUtf8 = info.Get<BString>(TorrentInfoFields.NameUtf8).ToString(encoding)` should be `DirectoryNameUtf8 = info.Get<BString>(TorrentInfoFields.NameUtf8)?.ToString(encoding)` in `TorrentParser.ParseMultiFileInfo`

The second one prevents getting `FullPathUtf8` if it doesn't exist. Instead of returning `null` it throws an exception. I guess the getter for `MultiFileInfo.FullPathUtf8` should be changed from `string.Join(System.IO.Path.DirectorySeparatorChar.ToString(), PathUtf8)` to something like `PathUtf8 != null ? string.Join(System.IO.Path.DirectorySeparatorChar.ToString(), PathUtf8) : null`...

Kind regards!

**Comment by Krusen** [comment]
You're right. There also was a potential parsing issue if the regular `name` field wasn't present for a multi file torrent.

New package will be available on NuGet soon.
