### ISSUE TITLE
How to read trackers?

### ISSUE THREAD

**Issue by holm76** [Krusen/BencodeNET#52]
I've been unsuccessful at reading out the tracker info in a torrent file. Debugging torrent.Trackers shows me a count of 1 but no matter what I do I cannot get the value. How do I get the Tracker info out?

torrent[TorrentFields.Announce] gives me errors and looping Trackers with another loop gives me nothing.

I've searched the interwebs and haven't found any answers there. I hope I can get an answer here.

**Comment by Krusen** [comment]
The `Trackers` property is a list of lists of strings - `IList<IList<string>>`. 

```csharp
// Get the first/single tracker
string firstTracker = torrent.Trackers.FirstOrDefault().FirstOrDefault();

// Collapse the lists into a single list of trackers
List<string> allTrackers = torrent.Trackers.SelectMany(x => x).ToList();
```
