### ISSUE TITLE
BencodeNET.Torrents.Torrent Parse Stream

### ISSUE THREAD

**Issue by longdoer** [Krusen/BencodeNET#57]
![image](https://user-images.githubusercontent.com/16441085/150128557-7c5e9930-b1a0-497c-8b05-42f809b3adf6.png)

but it doesn't work now

**Comment by Krusen** [comment]
What doesn't work?

**Comment by longdoer** [comment]
Thank you for answering me. I want to modify torrent and return it to the API file stream
![image](https://user-images.githubusercontent.com/16441085/150147606-574da226-2b63-4852-9766-ed71093f0633.png)

**Comment by Krusen** [comment]
I still don't see what your issue is.
But it doesn't seem to be related to this library.
