### ISSUE TITLE
Improve implementation of torrent files

### ISSUE THREAD

**Issue by abdullah2993** [Krusen/BencodeNET#7]
Any plans on providing first class support for parsing torrent files?

**Comment by Krusen** [comment]
I don't have any current plans for this project, but I'm open for suggestions. 
What features are you looking for?

**Comment by abdullah2993** [comment]
Who about parsing the complete torrent file at once. For example. Instead of exposing [Info](https://github.com/Krusen/BencodeNET/blob/master/BencodeNET.Net45/Objects/TorrentFile.cs#L15) as a [BDictionary](https://github.com/Krusen/BencodeNET/blob/master/BencodeNET.Net45/Objects/BDictionary.cs) It should expose the appropriate Properties with appropriate Types.

**Comment by hennyce** [comment]
Prehaps you could consider creating a feature to show seeders and leechers
for the current torrent.
I would even be willing to pay you to do it

**Comment by abdullah2993** [comment]
@hennyce IMO this feature is out of scope for this project but you can implement it with ease after parsing the tracker list. Take a look [here](https://wiki.theory.org/BitTorrentSpecification#Tracker_.27scrape.27_Convention)

**Comment by Krusen** [comment]
@Abdullah2993 Just wanted to let you know that I'm working on this. I'm pretty far but I don't have an ETA. I will probably publish the branch soon so you can have a look if you want to give some feedback.

**Comment by BoKKeR** [comment]
What about magnet link support ? would make this library the n.1 choice for c#. adding filesize for torrent.files would be awesome too :) yesterdays release was amazing. working as it should.

**Comment by Krusen** [comment]
> What about magnet link support?

I've added support for creating Magnet links for a torrent as well - I guessed that was what you were asking for?
